# Generated by Django 4.0.3 on 2022-03-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='email',
        ),
    ]
